[colors.primary]
background = '#09070d'
foreground = '#f0f0f0'

[colors.selection]
text = '#f0f0f0'
background = '#5b878c'

[colors.cursor]
text = '#09070d'
cursor = '#49ccd2'

[colors.normal]
black   = '#130f1a'
red     = '#f14481'
green   = '#49d254'
yellow  = '#fff148'
blue    = '#2bc0c7'
magenta = '#005c61'
cyan    = '#49ccd2'
white   = '#cbdbdc'

[colors.bright]
black   = '#7b8788'
red     = '#ff82ae'
green   = '#88fc92'
yellow  = '#fff68a'
blue    = '#66e1e7'
magenta = '#8af9ff'
cyan    = '#b4fbff'
white   = '#f6feff'
