set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'nhdaly/tmux-better-mouse-mode'
set -g @scroll-speed-num-lines-per-scroll 1
set -g mouse on
set -g history-limit 100000
set -g status-style "bg=default"

run '~/.tmux/plugins/tpm/tpm'
