# The one list of what this repo deploys, and where.
#
# configure.sh reads it left-to-right (repo → live) and doctor.sh reads it to
# check the two still agree. Before this file those two each carried their own
# copy of the list: 19 of the pairs were written out twice and a further 13
# paths were spelled again in doctor.sh, so keeping them in step was a manual
# job.
#
# The capture/ scripts used to read it right-to-left as well, for the handful of
# files a GUI owned. That was DankMaterialShell's settings, and with those gone
# every row here is now written by this repo and only by this repo — capture/
# deals exclusively in things that aren't in the table at all (config.kdl, the
# wallpaper images, the VS Code extension list, the package manifest).
#
# It had already gone wrong. `config/niri/dms/laptop.kdl` was deployed by
# configure.sh, was not in .gitignore, and was never pulled back — so on a
# laptop, every edit to the live file was silently discarded by the next
# install. Declaring the direction once makes that class of bug unrepresentable.
#
# ─── format ───────────────────────────────────────────────────────────────────
#
#   <path in repo>|<path relative to $HOME>|<kind>
#
# kinds:
#   copy      plain file. Copied out, pulled back.
#   exec      as copy, plus the executable bit on the way out.
#   laptop    only deployed on laptops. Nothing captures it back: it is a file
#             you edit in the repo, and a desktop has no copy to capture anyway.
#
# There used to be a fourth, `merge`, for a file the app owned and grew keys in
# — deploying merged rather than replaced so a re-install couldn't delete every
# key the repo's snapshot predated. Only DankMaterialShell's two settings files
# ever used it, and it went with them: waybar and mako read what we write and
# write nothing back. merge_json in lib/common.sh went at the same time.
#
# ─── deliberately NOT in here ─────────────────────────────────────────────────
#
# Four things stay as explicit code, because expressing them as table rows would
# mean inventing a kind per special case and the table would stop being readable:
#
#   config/niri/config.kdl   assembled with the laptop include appended before
#                            the compare, and stripped again on the way back
#   wallpaper/images/        a directory mirror, not a file pair
#   Code/extensions.txt      generated by `code --list-extensions`
#   the seeded stubs         niri-tasks.kdl, window-rules-active
#                            — created only when absent, never overwritten
#
# If you find yourself adding a fourth kind, that is the signal to write the step
# out longhand instead.

DOTFILES_MAP=(
    # shell
    "home/.bashrc|.bashrc|copy"
    "home/.profile|.profile|copy"

    # taskwarrior — the data location is all that matters to niri-tasks
    "home/.taskrc|.taskrc|copy"

    # tmux
    "home/.tmux.conf|.tmux.conf|copy"

    # niri — config.kdl is handled separately, see above
    "config/niri/window-rules/toggle.sh|.config/niri/window-rules/toggle.sh|exec"
    # Holds one lock for every shortcut that opens a popup, so a second one
    # cannot open on top of the first. niri-tasks' binds take the same lock by
    # path without going through this script — see the comment in it.
    "config/niri/popup-guard.sh|.config/niri/popup-guard.sh|exec"
    "config/niri/window-rules/normal.kdl|.config/niri/window-rules/normal.kdl|copy"
    "config/niri/window-rules/focus.kdl|.config/niri/window-rules/focus.kdl|copy"
    "config/niri/laptop.kdl|.config/niri/laptop.kdl|laptop"

    # wallpaper — one directory in the repo, four destinations on disk across
    # three trees, which is exactly why it is a feature directory rather than
    # part of the mirror. picker.ini lands in fuzzel's config rather than niri's
    # because fuzzel is what reads it, even though only the wallpaper bind does.
    "wallpaper/apply.sh|.config/niri/wallpaper-apply.sh|exec"
    "wallpaper/pick.sh|.config/niri/wallpaper-pick.sh|exec"
    "wallpaper/picker.ini|.config/fuzzel/wallpaper-picker.ini|copy"
    "wallpaper/swww-daemon.service|.config/systemd/user/swww-daemon.service|copy"

    # fuzzel — the launcher on Mod+Space. The other fuzzel configs are not here:
    # picker.ini is a symlink niri-tasks installs, and wallpaper-picker.ini goes
    # out with the wallpaper feature above.
    "config/fuzzel/fuzzel.ini|.config/fuzzel/fuzzel.ini|copy"

    # ghostty — its `command =` line is rewritten after deploy
    "config/ghostty/config.ghostty|.config/ghostty/config.ghostty|copy"

    # waybar + mako — what replaced DankMaterialShell. Plain copies, which is
    # the whole difference: nothing writes to these but us, so there is no
    # settings file growing keys underneath the repo and no merge to do.
    "config/waybar/config.jsonc|.config/waybar/config.jsonc|copy"
    "config/waybar/style.css|.config/waybar/style.css|copy"
    "config/mako/config|.config/mako/config|copy"

    # VS Code — note the live path is not the repo path
    "config/Code/settings.json|.config/Code/User/settings.json|copy"
)

# Split one row. Sets REPO_PATH / HOME_PATH / KIND for the caller.
#
# A function rather than an inline IFS read at each call site, so the three
# consumers cannot disagree about the field order.
map_entry() {
    local row="$1"
    REPO_PATH="${row%%|*}"
    local rest="${row#*|}"
    HOME_PATH="${rest%%|*}"
    KIND="${rest##*|}"
}
