# The one list of what this repo deploys, and where.
#
# configure.sh reads it left-to-right (repo → live), update.sh reads it
# right-to-left (live → repo), and doctor.sh reads it to check the two still
# agree. Before this file those three each carried their own copy of the list:
# 19 of the pairs were written out twice and a further 13 paths were spelled
# again in doctor.sh, so keeping them in step was a manual job.
#
# It had already gone wrong. `config/niri/dms/laptop.kdl` was deployed by
# configure.sh, was not in .gitignore, and was never pulled back — so on a
# laptop, every edit to the live file was silently discarded by the next
# install. Declaring the direction once makes that class of bug unrepresentable.
#
# ─── format ───────────────────────────────────────────────────────────────────
#
#   <path in repo>|<path relative to $HOME>|<kind>
#
# kinds:
#   copy      plain file. Copied out, pulled back.
#   exec      as copy, plus the executable bit on the way out.
#   merge     the app owns the live file and grows keys in it, so deploying
#             merges rather than replaces (see merge_json). Pulled back whole.
#   laptop    only deployed on laptops; pulled back only if the live file is
#             there, quietly, because on a desktop it never will be.
#
# ─── deliberately NOT in here ─────────────────────────────────────────────────
#
# Four things stay as explicit code, because expressing them as table rows would
# mean inventing a kind per special case and the table would stop being readable:
#
#   config/niri/config.kdl   assembled with the laptop include appended before
#                            the compare, and stripped again on the way back
#   wallpaper/images/        a directory mirror, not a file pair
#   Code/extensions.txt      generated by `code --list-extensions`
#   the seeded stubs         dms/binds.kdl, niri-tasks.kdl, window-rules-active
#                            — created only when absent, never overwritten
#
# If you find yourself adding a fifth kind, that is the signal to write the step
# out longhand instead.

DOTFILES_MAP=(
    # shell
    "home/.bashrc|.bashrc|copy"
    "home/.profile|.profile|copy"

    # taskwarrior — the data location is all that matters to niri-tasks
    "home/.taskrc|.taskrc|copy"

    # tmux
    "home/.tmux.conf|.tmux.conf|copy"

    # niri — config.kdl is handled separately, see above
    "config/niri/window-rules/toggle.sh|.config/niri/window-rules/toggle.sh|exec"
    "config/niri/window-rules/normal.kdl|.config/niri/window-rules/normal.kdl|copy"
    "config/niri/window-rules/focus.kdl|.config/niri/window-rules/focus.kdl|copy"
    "config/niri/dms/laptop.kdl|.config/niri/dms/laptop.kdl|laptop"

    # wallpaper — one directory in the repo, three destinations on disk, which
    # is exactly why it is a feature directory rather than part of the mirror.
    "wallpaper/wallpaper-sync.sh|.config/niri/wallpaper-sync.sh|exec"
    "wallpaper/swww-daemon.service|.config/systemd/user/swww-daemon.service|copy"
    "wallpaper/wallpaper-sync.service|.config/systemd/user/wallpaper-sync.service|copy"

    # ghostty — its `command =` line is rewritten after deploy
    "config/ghostty/config.ghostty|.config/ghostty/config.ghostty|copy"

    # DankMaterialShell — settings.json and plugin_settings.json are merged, not
    # replaced: DMS grows keys in them with each release and a flat copy would
    # delete every key our snapshot predates.
    "config/DankMaterialShell/settings.json|.config/DankMaterialShell/settings.json|merge"
    "config/DankMaterialShell/plugin_settings.json|.config/DankMaterialShell/plugin_settings.json|merge"
    "config/DankMaterialShell/firefox.css|.config/DankMaterialShell/firefox.css|copy"
    "config/DankMaterialShell/themes/peaceAndQuiet/theme.json|.config/DankMaterialShell/themes/peaceAndQuiet/theme.json|copy"

    # VS Code — note the live path is not the repo path
    "config/Code/settings.json|.config/Code/User/settings.json|copy"
)

# Split one row. Sets REPO_PATH / HOME_PATH / KIND for the caller.
#
# A function rather than an inline IFS read at each call site, so the three
# consumers cannot disagree about the field order.
map_entry() {
    local row="$1"
    REPO_PATH="${row%%|*}"
    local rest="${row#*|}"
    HOME_PATH="${rest%%|*}"
    KIND="${rest##*|}"
}
