# The one list of what this repo deploys, and where.
#
# configure.sh reads it left-to-right (repo → live) and doctor.sh reads it to
# check the two still agree. Before this file those two each carried their own
# copy of the list: 19 of the pairs were written out twice and a further 13
# paths were spelled again in doctor.sh, so keeping them in step was a manual
# job.
#
# The capture/ scripts used to read it right-to-left as well, for the handful of
# files a GUI owned. That was DankMaterialShell's settings, and with those gone
# capture/ deals exclusively in things that aren't in the table at all
# (config.kdl, the wallpaper images, the VS Code extension list, the package
# manifest).
#
# One row is still not ours alone: config/Code/settings.json. VS Code rewrites
# it whenever you change a setting in the UI, and it prunes keys it considers
# dead — it dropped window.newWindowProfile here because the profile it named
# did not exist on this machine. So a `copy` deploys the repo's version over
# whatever you last clicked, and there is no capture script to bring it back.
# Live with it by editing settings in the repo, or notice the drift in
# doctor.sh; what you must not do is assume this file holds still.
#
# It had already gone wrong. `config/niri/dms/laptop.kdl` was deployed by
# configure.sh, was not in .gitignore, and was never pulled back — so on a
# laptop, every edit to the live file was silently discarded by the next
# install. Declaring the direction once makes that class of bug unrepresentable.
#
# ─── format ───────────────────────────────────────────────────────────────────
#
#   <path in repo>|<path relative to $HOME>|<kind>
#
# kinds:
#   copy      plain file. Copied out, pulled back.
#   exec      as copy, plus the executable bit on the way out.
#   laptop    only deployed on laptops, and removed from a desktop. Nothing
#             captures it back: it is a file you edit in the repo, and a
#             desktop has no copy to capture anyway.
#   desktop   the same the other way round: only on desktops, removed from a
#             laptop.
#
# There used to be a fourth, `merge`, for a file the app owned and grew keys in
# — deploying merged rather than replaced so a re-install couldn't delete every
# key the repo's snapshot predated. Only DankMaterialShell's two settings files
# ever used it, and it went with them: waybar and mako read what we write and
# write nothing back. merge_json in lib/common.sh went at the same time.
#
# ─── deliberately NOT in here ─────────────────────────────────────────────────
#
# Four things stay as explicit code, because expressing them as table rows would
# mean inventing a kind per special case and the table would stop being readable:
#
#   config/niri/config.kdl   assembled with the machine-type include appended before
#                            the compare, and stripped again on the way back
#   wallpaper/images/        a directory mirror, not a file pair
#   Code/extensions.txt      generated by `code --list-extensions`
#   the seeded stubs         niri-tasks.kdl, window-rules-active
#                            — created only when absent, never overwritten
#
# If you find yourself adding a kind for one special case, that is the signal to write the step
# out longhand instead.

DOTFILES_MAP=(
    # shell
    "home/.bashrc|.bashrc|copy"
    "home/.profile|.profile|copy"

    # taskwarrior — the data location is all that matters to niri-tasks
    "home/.taskrc|.taskrc|copy"

    # tmux
    "home/.tmux.conf|.tmux.conf|copy"

    # niri — config.kdl is handled separately, see above
    "config/niri/window-rules/toggle.sh|.config/niri/window-rules/toggle.sh|exec"
    "config/niri/window-rules/normal.kdl|.config/niri/window-rules/normal.kdl|copy"
    "config/niri/window-rules/focus.kdl|.config/niri/window-rules/focus.kdl|copy"
    "config/niri/laptop.kdl|.config/niri/laptop.kdl|laptop"
    "config/niri/desktop.kdl|.config/niri/desktop.kdl|desktop"

    # wallpaper — one directory in the repo, four destinations on disk across
    # three trees, which is exactly why it is a feature directory rather than
    # part of the mirror. picker.ini lands in fuzzel's config rather than niri's
    # because fuzzel is what reads it, even though only the wallpaper bind does.
    "wallpaper/apply.sh|.config/niri/wallpaper-apply.sh|exec"
    "wallpaper/pick.sh|.config/niri/wallpaper-pick.sh|exec"
    "wallpaper/picker.ini|.config/fuzzel/wallpaper-picker.ini|copy"
    "wallpaper/swww-daemon.service|.config/systemd/user/swww-daemon.service|copy"

    # fuzzel — the launcher on Mod+Space. The other fuzzel configs are not here:
    # picker.ini is a symlink niri-tasks installs, and wallpaper-picker.ini goes
    # out with the wallpaper feature above.
    "config/fuzzel/fuzzel.ini|.config/fuzzel/fuzzel.ini|copy"

    # ghostty — its `command =` line is rewritten after deploy
    "config/ghostty/config.ghostty|.config/ghostty/config.ghostty|copy"

    # waybar + mako — what replaced DankMaterialShell. Plain copies, which is
    # the whole difference: nothing writes to these but us, so there is no
    # settings file growing keys underneath the repo and no merge to do.
    "config/waybar/config.jsonc|.config/waybar/config.jsonc|copy"
    "config/waybar/style.css|.config/waybar/style.css|copy"
    # battery + backlight for the top bar; see the include in config.jsonc
    "config/waybar/laptop.jsonc|.config/waybar/laptop.jsonc|laptop"
    "config/mako/config|.config/mako/config|copy"

    # Desktop entries shadowing stock ones from ~/.local/share/applications —
    # outside ~/.config because that is where XDG looks for them, and that is
    # not negotiable. GNOME Settings, so it is both visible in the launcher and
    # able to start; ChatGPT, so it starts on Wayland rather than Xwayland.
    "config/applications/org.gnome.Settings.desktop|.local/share/applications/org.gnome.Settings.desktop|copy"
    "config/applications/chatgpt.desktop|.local/share/applications/chatgpt.desktop|copy"

    # ChatGPT from a terminal — the same Wayland flags as the desktop entry,
    # found ahead of /usr/bin/chatgpt because .profile puts ~/.local/bin first.
    "home/.local/bin/chatgpt|.local/bin/chatgpt|exec"

    # VS Code — note the live path is not the repo path
    "config/Code/settings.json|.config/Code/User/settings.json|copy"
)

# Split one row. Sets REPO_PATH / HOME_PATH / KIND for the caller.
#
# A function rather than an inline IFS read at each call site, so the three
# consumers cannot disagree about the field order.
map_entry() {
    local row="$1"
    REPO_PATH="${row%%|*}"
    local rest="${row#*|}"
    HOME_PATH="${rest%%|*}"
    KIND="${rest##*|}"
}
